### ISSUE TITLE
Html Webpack Plugin

### ISSUE THREAD

**Issue by shevdi** [Gulyaev52/resume#1]
У меня вылазит ошибка при сборке
  SyntaxError: Unexpected token {  
  - index.js:221 HtmlWebpackPlugin.evaluateCompilationResult
    [resume]/[html-webpack-plugin]/index.js:221:18

Работаешь под виндой?

**Comment by Gulyaev52** [comment]
Да, работаю под виндой

**Comment by shevdi** [comment]
Вроде как с ошибкой удалось справиться в FlatUI , переставив вебпак. Но после этого вылазят неустановленные пакеты. Все добавил в зависимости в package.json?
