### ISSUE TITLE
software блок

### ISSUE THREAD

**Issue by shevdi** [Gulyaev52/resume#2]
Можно верстку сделать еще немного гибче.
Так же как и с column в software сделай на маленьких экранах навыки в один столбец.

**Comment by Gulyaev52** [comment]
Я не много не понял что изменить, так как в блоке skills все элементы расположены и так в один столбец. На всякий случай спрошу: ты же ветку refactoring смотришь?

**Comment by shevdi** [comment]
Да, в рефакторинге. Я про блок software. Там, где photoshop, deamweaver и т.п.
